apiVersion: v2
name: arch-eventing
description: OTUS architect course, homework 15 "eventing"

type: application

version: 0.1.0
appVersion: "latest"

dependencies:
  - name: postgresql
    version: 9.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - hw-database

  - name: rabbitmq
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
    tags:
      - hw-rabbit
