apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arch-eventing.fullname" . }}-notification
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arch-eventing.labels.notification" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "arch-eventing.selectorLabels.notification" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "arch-eventing.selectorLabels.notification" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-notification.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-notification
          image: "{{ .Values.image.notification }}:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: "{{ include "arch-eventing.name" . }}-notification"
            - secretRef:
                name: "{{ include "arch-eventing.name" . }}-notification"
          env:
            - name: SERVER_PORT
              value: "8080"
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 10
            periodSeconds: 5
