apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "arch-eventing.fullname" . }}-notification
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: {{ .Values.ingress.pathPrefix }}/notification($|/)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "arch-eventing.fullname" . }}-notification
                port:
                  name: "http"
