apiVersion: v1
kind: Service
metadata:
  name: {{ include "arch-eventing.fullname" . }}-billing
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "arch-eventing.labels.billing" . | nindent 4 }}
spec:
  type: {{ .Values.service.billing.type }}
  ports:
    - port: {{ .Values.service.billing.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "arch-eventing.selectorLabels.billing" . | nindent 4 }}
