apiVersion: v1
kind: Service
metadata:
  name: {{ include "arch-eventing.fullname" . }}-notification
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "arch-eventing.labels.notification" . | nindent 4 }}
spec:
  type: {{ .Values.service.notification.type }}
  ports:
    - port: {{ .Values.service.notification.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "arch-eventing.selectorLabels.notification" . | nindent 4 }}
